// tfvar interface
variable "location" {}
variable "deployer_rg_name" {}
variable "vnet_mgmt_arm_id" {}
variable "vnet_mgmt_name" {}
variable "sub_mgmt_name" {}
variable "deployer_vnet_address_space" {}
variable "deployer_subnet_prefix" {}
variable "enable_secure_transfer" {}
variable "sub_mgmt_arm_id" {}
variable "sub_mgmt_nsg_arm_id" {}
variable "sub_mgmt_nsg_name" {}
variable "sub_mgmt_nsg_allowed_ips" {}
variable "deployer_size" {}
variable "deployer_disk_type" {}
variable "deployer_os_source_image_id" {}
variable "deployer_os" {}
variable "deployer_authentication_type" {}
variable "deployer_authentication_username" {}
variable "deployer_authentication_password" {}
variable "deployer_sshkey_path_to_public_key" {}
variable "deployer_sshkey_path_to_private_key" {}
variable "deployer_private_ip_address" {}
